config/routes.rb
Rails.application.routes.draw do

#namespaceだと上手く作動しない
  resources :genres, only: [:show]
  resources :orders
  resources :cart_items, only: [:index, :create, :update, :destroy]
  delete 'cart_items' => 'cart_items#all_destroy', as: 'all_destroy'
  resources :orders, only: [:create, :new, :index, :show ,]
  resources :shipping_addresses, only: [:index, :create, :destroy, :edit, :update]
  resource :customers, only: [:show, :edit, :update]
  patch 'customers/quit' => 'customers#out', as: 'out'
  root to: "homes#top"
  resources :items, only: [:show, :index]
  get "home/about"=>"homes#about"
  get "order/about" => "orders#about"
  get "order/complete" => "orders#complete"

  devise_for :customers, controllers: {
  sessions:      'customers/sessions',
  passwords:     'customers/passwords',
  registrations: 'customers/registrations'
}

#ふっちー
  devise_for :admins, skip:[:registrations, :passwords], controllers: {
  sessions:      'admins/sessions',
}


  namespace :admins do
    resources :customers, only: [:index, :show, :edit, :update]
    resources :orders, only: [:index, :show, :update]
    #ふっちー
    resources :genres, only: [:index, :edit, :create, :update]
    resources :items, only: [:index, :edit, :new, :show, :create, :update]
  end

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/genre.rb
class Genre < ApplicationRecord
  has_many :items, dependent: :destroy

  validates :genre_name, presence: true
end

app/controllers/admin/genres_controller.rb
class Admin::GenresController < ApplicationController
  before_action :authenticate_admin!
  def index
    @genres = Genre.all
    @genre = Genre.new
  end

  def create
    @genre = Genre.new(genre_params)
    if @genre.save
      redirect_to admin_genres_path, notice: "ジャンルを追加しました"
    else
      @genres = Genre.all
      render :index
    end
  end

  def edit
    @genre = Genre.find(params[:id])
  end

  def update
    @genre = Genre.find(params[:id])
    if @genre.update(genre_params)
      redirect_to admin_genres_path, notice: "ジャンルを変更しました。"
    else
      render :edit
    end
  end

  private

  def genre_params
    params.require(:genre).permit(:genre_name)
  end
end

app/controllers/admins/genres_controller.rb
class Admins::GenresController < ApplicationController
  before_action :authenticate_admin!
  def index
    @genres = Genre.all
    @genre = Genre.new
  end

  def create
    @genre = Genre.new(genre_params)
    if @genre.save
      redirect_to admins_genres_path, notice: "ジャンルを追加しました"
    else
      @genres = Genre.all
      render :index
    end
  end

  def edit
    @genre = Genre.find(params[:id])
  end

  def update
    @genre = Genre.find(params[:id])
    if @genre.update(genre_params)
      redirect_to admins_genres_path, notice: "ジャンルを変更しました。"
    else
      render :edit
    end
  end

  private

  def genre_params
    params.require(:genre).permit(:genre_name)
  end
end

app/controllers/customers/genres_controller.rb
class GenresController < ApplicationController
  def show
    @genre = Genre.find(params[:id])
    @items = Item.where(genre_id: @genre.id).page(params[:page]).per(8)
    @genres = Genre.all
  end
end

app/helpers/admin/genres_helper.rb
module Admin::GenresHelper
end

app/helpers/admins/genres_helper.rb
module Admins::GenresHelper
end

app/views/admins/genres/edit.html.erb
<div class="container mb-5">
  <div class="row">
    <h3 class="mb-5 bg-light px-4 shadow">ジャンル編集</h3>
  </div>

  <%= form_with model: @genre, url: admins_genre_path(@genre.id),method: :patch, local: true do |f| %>
   <div class="row form_group">
     <%= f.label :"ジャンル名", class: "col-auto col-form-label" %>
     <div class="col-auto align-self-center"><%= f.text_field :genre_name %></div>
     <div class+"col-auto"><%= f.submit "変更を保存", class: 'btn btn-success bt-lg' %></div>
   </div>
  <% end %>
</div>

app/views/admins/genres/index.html.erb
<div class="container m-4">
  <div class="row">
    <h3 class="m-3 bg-light px-4 shadow">ジャンル一覧・追加</h3>
  </div>

  <%= form_with model: @genre, url: admins_genres_path(@genre.id),method: :post, local: true do |f| %>
    <div class="row form-group mt-3">
      <%= f.label :"ジャンル名", class: "col-auto col-form-label" %>
      <div class="col-auto align-self-center"><%= f.text_field :genre_name, autofocus: true, placeholder: "ジャンル名" %></div>
      <div class="col-auto"><%= f.submit "新規登録", class: 'btn btn-success' %></div>
    </div>
  <% end %>

  <div class="row mt-5">
    <div class="col-md-5">
      <table class="table table-hover shadow">

        <thead>
          <tr class="bg-light">
            <th class="pl-4">ジャンル</th>
            <th></th>
          </tr>
        </thead>

        <tbody>
          <% @genres.each do |genre| %>
           <tr>
             <td class='align-middle'><%= genre.genre_name %></td>
             <td class='text-right'><%= link_to "編集する", edit_admins_genre_path(genre.id), class: 'btn btn-success' %></td>
           </tr>
          <% end %>
        </tbody>

      </table>
    </div>
  </div>
</div>