config/routes.rb
Rails.application.routes.draw do

#namespaceだと上手く作動しない
  resources :genres, only: [:show]
  resources :orders
  resources :cart_items, only: [:index, :create, :update, :destroy]
  delete 'cart_items' => 'cart_items#all_destroy', as: 'all_destroy'
  resources :orders, only: [:create, :new, :index, :show ,]
  resources :shipping_addresses, only: [:index, :create, :destroy, :edit, :update]
  resource :customers, only: [:show, :edit, :update]
  patch 'customers/quit' => 'customers#out', as: 'out'
  root to: "homes#top"
  resources :items, only: [:show, :index]
  get "home/about"=>"homes#about"
  get "order/about" => "orders#about"
  get "order/complete" => "orders#complete"

  devise_for :customers, controllers: {
  sessions:      'customers/sessions',
  passwords:     'customers/passwords',
  registrations: 'customers/registrations'
}

#ふっちー
  devise_for :admins, skip:[:registrations, :passwords], controllers: {
  sessions:      'admins/sessions',
}


  namespace :admins do
    resources :customers, only: [:index, :show, :edit, :update]
    resources :orders, only: [:index, :show, :update]
    #ふっちー
    resources :genres, only: [:index, :edit, :create, :update]
    resources :items, only: [:index, :edit, :new, :show, :create, :update]
  end

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/cart_item.rb
class CartItem < ApplicationRecord
  belongs_to :customer
  belongs_to :item
end

app/controllers/cart_items_controller.rb
class CartItemsController < ApplicationController
      before_action :authenticate_customer!


  def index
     @cart_items = current_customer.cart_items
  end

  def create
    @cart_item = CartItem.new(cart_item_params)
    @cart_item.customer_id = current_customer.id
    @cart_item.item_id = params[:item_id]

    if @cart_item.save
      flash[:notice] = "@cart_item.item.nameをカートに追加しました。"
      redirect_to cart_items_path
    else
      flash[:alert] = "個数を選択してください"
      render "customers/items/show"
    end
  end

  def update
    @cart_item = CartItem.find(params[:id])
    @cart_item.update(cart_item_params)
    redirect_to cart_items_path
  end

  def destroy
    @cart_item = CartItem.find(params[:id])
    @cart_item.destroy
    flash.now[:alert] = "#{@cart_item.item.name}を削除しました"
    redirect_to cart_items_path
  end

  def all_destroy
    @cart_item = current_customer.cart_items
    @cart_item.destroy_all
    flash[:alert] = "カートの商品を全て削除しました"
    redirect_to cart_items_path
  end

   private

    def cart_item_params
      params.require(:cart_item).permit(:amount, :item_id, :customer_id)
    end



end

app/helpers/cart_items_helper.rb
module CartItemsHelper
end

app/views/cart_items/index.html.erb
<div class="row">
    <div class="col-md-12">
      <div>
        <strong class="information-link"><h3>ショッピングカート</h3></strong>
        <%= link_to "カートを空にする", all_destroy_path, method: :delete, class: "pull-right btn btn-danger" %>
      </div>
        <table class="table table-hover table-bordered col-xs-10" >
         <thead>
          <tr class="info">
            <th class="col-xs-3">商品名</th>
            <th class="col-xs-2">単価（税込み）</th>
            <th class="col-xs-1">数量</th>
            <th class="col-xs-1">小計</th>
            <th class="col-xs-1"></th>
          </tr>
         </thead>
         <tbody>
          <% @total_price=0 %>
          <% @cart_items.each do |cart_item| %>
          <tr>
            <td class="col-xs-3"><%= cart_item.item.name %></td>
            <td class="col-xs-2">¥<%= ((cart_item.item.price * 1.1).floor).to_s(:delimited, delimiter: ',') %></td>
            <td class="col-xs-1">
                <%= form_with model: cart_item, url: cart_item_path(cart_item) do |f| %>
                <p>
                  <%= f.number_field :amount, min:1, max:10000, step:1 %>
                  <%= f.submit "変更", class: "btn btn-primary" %>
                </p>
                <% end %>
            </td>
            <td class="col-xs-1">
                <%= (((cart_item.item.price).to_i * (cart_item.amount).to_i * 1.1).floor).to_s(:delimited, delimiter: ',') %>
            </td>
                <% @total_price += (((cart_item.item.price).to_i * (cart_item.amount).to_i * 1.1).floor) %>
            <td class="col-xs-1">
                <%= link_to "削除する", cart_item_path(cart_item.id), method: :DELETE, class: "btn btn-danger" %>
            </td>
          </tr>
          <% end %>
         </tbody>
        </table>

    </div>
</div>


<div class="col-xs-8">
    <span>
    <%= link_to "買い物を続ける", root_path, class: "btn btn-primary" %>
    </span>
</div>
<div class="col-xs-4">
    <table class="table table-bordered">
        <tr>
            <td class="info col-xs-2"><strong>合計金額</strong></td>
            <td class="col-xs-2">¥<P><%= @total_price %></P></td>
        </tr>
    </table>
</div>

<div class = "col-xs-4 col-xs-offset-4">
    <span>
        <%= link_to "情報入力に進む", new_order_path, class: "col-xs-12 btn btn-success"%>
    </span>
    </div>
</div>