config/routes.rb
Rails.application.routes.draw do

#namespaceだと上手く作動しない
  resources :genres, only: [:show]
  resources :orders
  resources :cart_items, only: [:index, :create, :update, :destroy]
  delete 'cart_items' => 'cart_items#all_destroy', as: 'all_destroy'
  resources :orders, only: [:create, :new, :index, :show ,]
  resources :shipping_addresses, only: [:index, :create, :destroy, :edit, :update]
  resource :customers, only: [:show, :edit, :update]
  patch 'customers/quit' => 'customers#out', as: 'out'
  root to: "homes#top"
  resources :items, only: [:show, :index]
  get "home/about"=>"homes#about"
  get "order/about" => "orders#about"
  get "order/complete" => "orders#complete"

  devise_for :customers, controllers: {
  sessions:      'customers/sessions',
  passwords:     'customers/passwords',
  registrations: 'customers/registrations'
}

#ふっちー
  devise_for :admins, skip:[:registrations, :passwords], controllers: {
  sessions:      'admins/sessions',
}


  namespace :admins do
    resources :customers, only: [:index, :show, :edit, :update]
    resources :orders, only: [:index, :show, :update]
    #ふっちー
    resources :genres, only: [:index, :edit, :create, :update]
    resources :items, only: [:index, :edit, :new, :show, :create, :update]
  end

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/item.rb
class Item < ApplicationRecord
  belongs_to :genre
  has_many :order_details
  has_many :cart_items

  has_one_attached :image

  validates :name, length: {maximum: 20, minimum: 2},  presence:true
  validates :introduction, :price, presence: true
  validates  :status, inclusion: {in: [true, false]}


  # 消費税の計算 roundで小数点の切り上げ
  def add_tax_price
        (self.price * 1.10).round
  end
  #itemがcart_itemの所有者
  has_many :cart_items, dependent: :destroy


end

app/controllers/admin/items_controller.rb
class Admin::ItemsController < ApplicationController
  before_action :authenticate_admin!

  def index
   @items = Item.all
  end

  def new
   @item = Item.new
  end

  def create
   @item = Item.new(item_params)
   if @item.save!
     redirect_to admin_item_path(@item.id)
   else
     render :new
   end
  end

  def show
    @item = Item.find(params[:id])
  end

  def edit
    @item = Item.find(params[:id])
  end

  def update
    @item = Item.find(params[:id])
    if @item.update(item_params)
      redirect_to admin_item_path(@item.id)
    else
      render :edit
    end
  end

  private

  def item_params
    params.require(:item).permit(:name, :introduction, :image, :price, :status, :genre_id)
  end

end

app/controllers/admins/items_controller.rb
class Admins::ItemsController < ApplicationController
  before_action :authenticate_admin!

  def index
   @items = Item.all
  end

  def new
   @item = Item.new
  end

  def create
   @item = Item.new(item_params)
   if @item.save
     redirect_to admins_item_path(@item.id)
   else
     render :new
   end
  end

  def show
    @item = Item.find(params[:id])
  end

  def edit
    @item = Item.find(params[:id])
  end

  def update
    @item = Item.find(params[:id])
    if @item.update(item_params)
      redirect_to admins_item_path(@item.id)
    else
      render :edit
    end
  end

  private

  def item_params
    params.require(:item).permit(:name, :introduction, :image, :price, :status, :genre_id)
  end

end

app/controllers/items_controller.rb
class ItemsController < ApplicationController

 def index
  @genres = Genre.all
  @items = Item.all.page(params[:page]).per(8)
  @items_all = Item.all
 end


 def show
  @item = Item.find(params[:id])
  @cart_item = CartItem.new
  @genres = Genre.all
 end

end

app/helpers/admins/items_helper.rb
module Admins::ItemsHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/views/items/_sidebar.html.erb
    <div >
      ジャンル
    </div>

    <table class="table table-bordered table-hover text-center" >
      <tr>
        <td>
          <%= link_to "全商品を表示", items_path %>
        </td>
      </tr>

      <% genres.each do |genre| %>
        <tr>
          <td>
            <%= link_to genre.genre_name, genre_path(genre.id) %>
            </td>
        </tr>
           <% end %>

    </table>

app/views/items/index.html.erb
<div class="container">
	<div class="row">
	  <div class="col-2 px-5 px-sm-0 mt-4 ">
	  	<%= render 'items/sidebar', genres: @genres %>
	  </div>
	  <div class="col-10 mx-auto mt-4">

     <h2 class="font-weight-bold">商品一覧(全<%= @items_all.count %>件)</h2>
	     <div class="ml-3">
		  </div>


	  <div class="row">
	    <% @items.each do |item| %>
        <div class="col-3">
	  		  <%= link_to item_path(item.id) do %>
	  		  	<%= image_tag item.image, size:"200x200" %><br>
	  		     <%= item.name %>
	  		 	  ¥<%= item.price.to_s(:delimited, delimiter: ',') %>
	  		  <% end %>
	  	  </div>
	    <% end %>
	  </div>

	</div>
	<div style="text-align: center;"><%= paginate @items %></div>
	</div>
</div>

app/views/items/show.html.erb
<div class="row">
	<div class="col-2">
	<%= render 'items/sidebar', genres: @genres %>
	</div>


<div class="container">
	<br>
	<div class="col-xs-5">
		<p><%= image_tag @item.image, size:'380x300' %></p>
	</div>

	<div class="col-xs-5">
		<%= form_with model: @cart_item , url: cart_items_path(item_id: @item), method: :post do |f| %>
		<h3><%= @item.name %></h3>
		<p><%= @item.introduction %></p>
	</div>

	<div class="row">
		<div class="col-xs-5">
			<p class="item-content2">
				¥ <%= ((@item.price*1.1).floor).to_s(:delimited, delimiter: ',') %> (税込)
				<span>　　</span><%= f.select :amount, [['1個', 1], ['2個', 2], ['3個', 3], ['4個', 4], ['5個', 5], ['6個', 6], ['7個', 7], ['8個', 8], ['9個', 9]], {:prompt => "個数選択"} %>
			</p>
		</div>

			<div class="col-xs-5">
			  <p><%= f.submit "カートに入れる", class:"btn btn-primary" %></p>
			</div>
			<% end %>
	</div>
	</div>
</div>